# Generated by Django 2.2.9 on 2020-01-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tests',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
